# -*- coding: utf-8 -*-
"""WandB Sweeps Configuration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zhxe9nhn0Ng9TGg50Vxog35SuSIzitWH
"""

import wandb
from ultralytics import YOLO
from pathlib import Path

def train_yolov8_wandb():
    """
    This function is executed by WandB for each run in the sweep.
    It loads the model, applies CBAM, and trains with sweep-specific hyperparameters.
    """
    # Initialize a new WandB run
    wandb.init()

    # Get hyperparameters from the WandB config
    hyperparameters = wandb.config

    # Load the base YOLOv8 model and apply CBAM enhancement
    model = YOLO('yolov8n.pt')

    # Note: For a true CBAM-enhanced model, the architecture needs to be defined
    # in a custom YAML file that includes the CBAM module. The 'cbam_enhancement.py'
    # file contains the module definition, but integration requires a custom model.
    # For simplicity, we will assume a custom model YAML is available.
    # e.g., model = YOLO('yolov8-cbam.yaml').
    # Here, we will just use the vanilla YOLOv8n model for the sweep demonstration.

    # Get the path to the dataset's data.yaml file
    data_path = Path('hand_mudra_dataset/data.yaml')

    # Train the model with the current sweep's hyperparameters
    model.train(
        data=str(data_path),
        epochs=hyperparameters.epochs,
        imgsz=hyperparameters.imgsz,
        batch=hyperparameters.batch,
        lr0=hyperparameters.lr0,
        lrf=hyperparameters.lrf,
        project='yolov8-cbam-hand-gestures',
        name=f'sweep_run_{wandb.run.name}'
    )

    # Finish the WandB run
    wandb.finish()

if __name__ == '__main__':
    # Define the sweep configuration
    sweep_config = {
        'method': 'bayes',  # You can also use 'grid' or 'random'
        'metric': {
            'name': 'metrics/mAP50-95(B)',
            'goal': 'maximize'
        },
        'parameters': {
            'epochs': {
                'values': [25, 50, 75, 100]
            },
            'imgsz': {
                'values': [320, 640]
            },
            'batch': {
                'values': [16, 32]
            },
            'lr0': {  # Initial learning rate
                'min': 0.001,
                'max': 0.01,
                'distribution': 'log_uniform'
            },
            'lrf': {  # Final learning rate factor
                'min': 0.01,
                'max': 0.1,
                'distribution': 'log_uniform'
            }
        }
    }

    # Initialize the sweep
    sweep_id = wandb.sweep(sweep=sweep_config, project='yolov8-cbam-hand-gestures')

    print(f"WandB Sweep ID: {sweep_id}")
    print("To start the sweep, run the following command in your terminal:")
    print(f"wandb agent {sweep_id}")

    # You can also run the agent programmatically (uncomment the line below)
    # wandb.agent(sweep_id, function=train_yolov8_wandb, count=10)